// Regenerates renderer/emojis.js from the unicode-emoji-json dataset.
// Run: node scripts/gen-emojis.js   (re-run after bumping the dataset)
//
// Output keeps the existing window.EMOJI_GROUPS shape — each entry is
// [shortcode, char, name] (name added for picker search) — plus the
// shortcode map / replaceShortcodes / QUICK_REACTIONS the app already uses.
const fs = require('fs');
const path = require('path');
const data = require('unicode-emoji-json');

const GROUP_ORDER = [
  'Smileys & Emotion', 'People & Body', 'Animals & Nature', 'Food & Drink',
  'Travel & Places', 'Activities', 'Objects', 'Symbols', 'Flags',
];
const byGroup = new Map(GROUP_ORDER.map((g) => [g, []]));
for (const [char, meta] of Object.entries(data)) {
  const arr = byGroup.get(meta.group);
  if (arr) arr.push([`:${meta.slug}:`, char, meta.name]);
}
const groups = GROUP_ORDER.map((g) => ({ name: g, list: byGroup.get(g) }));

// Keep a few legacy shortcodes working for people who type them.
// Short, muscle-memory aliases that don't match unicode-emoji-json's canonical
// names (e.g. :thinking: vs :thinking_face:). Without these the only shortcodes
// that expand are the long canonical forms.
const ALIASES = {
  ':+1:': '👍', ':-1:': '👎', ':thumbsup:': '👍', ':thumbsdown:': '👎',
  ':smile:': '😄', ':grin:': '😁', ':joy:': '😂', ':rofl:': '🤣',
  ':sweat_smile:': '😅', ':laughing:': '😆', ':wink:': '😉', ':blush:': '😊',
  ':heart_eyes:': '😍', ':thinking:': '🤔', ':thinking_face:': '🤔',
  ':wave:': '👋', ':muscle:': '💪', ':ok_hand:': '👌', ':raised_hands:': '🙌',
  ':point_up:': '☝️', ':heart:': '❤️', ':broken_heart:': '💔',
  ':tada:': '🎉', ':fire:': '🔥', ':eyes:': '👀', ':100:': '💯',
  ':boom:': '💥', ':zap:': '⚡', ':sob:': '😭', ':cry:': '😢', ':sweat:': '😓',
  ':rocket:': '🚀', ':star:': '⭐', ':sparkles:': '✨', ':check:': '✅',
  ':white_check:': '✅', ':heavy_check_mark:': '✔️', ':x:': '❌',
  ':warning:': '⚠️', ':pray:': '🙏', ':clap:': '👏',
};

const out = `// AUTO-GENERATED by scripts/gen-emojis.js from unicode-emoji-json — do not edit by hand.
// Each list entry is [shortcode, char, name]; name powers picker search.
window.EMOJI_GROUPS = ${JSON.stringify(groups)};
window.EMOJI_ALIASES = ${JSON.stringify(ALIASES)};
window.EMOJI_SHORTCODES = (() => {
  const map = new Map();
  for (const g of window.EMOJI_GROUPS) for (const [code, emoji] of g.list) map.set(code, emoji);
  for (const [code, emoji] of Object.entries(window.EMOJI_ALIASES)) map.set(code, emoji);
  return map;
})();
window.replaceShortcodes = (text) =>
  text.replace(/:[a-z0-9_+\\-]+:/gi, (m) => window.EMOJI_SHORTCODES.get(m.toLowerCase()) || m);
window.QUICK_REACTIONS = ['👍', '❤️', '🎉', '😂', '🙏', '🔥', '👀', '✅'];
`;
fs.writeFileSync(path.join(__dirname, '..', 'renderer', 'emojis.js'), out);
console.log(`wrote renderer/emojis.js — ${groups.reduce((n, g) => n + g.list.length, 0)} emoji in ${groups.length} groups`);
